Visit.delete_all
Visit.create(:venue => 'The Westin - Alice in Wonderland Theme', :city => 'Sydney- Australia', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 2.5, :tea => 5, :scones => 4, :savoury => 4, :sweets => 4, :service => 5, :bonus => 0, :comments => 'I was shocked by the improvement in this since our last visit. The service was very attentive, the unlimited tea let us choose a few different types to try, the savoury was delicious - all I wanted was a bit more - and the sweets looked cute (alice in wonderland theme) and tasted quite nice.', :price_cents => 49, :price_currency =>'AUD')
Visit.create(:venue => 'Ritz Hotel London', :city => 'United Kingdom', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 5, :tea => 5, :scones => 5, :savoury => 5, :sweets => 5, :service => 5, :bonus => 2, :comments => 'This was our very first high tea, and we rated in retrospect almost 2 years later, maybe this accounts for its perfect rating. BUT it was very fabulous, with string quartet, piano, champagne, and beautiful surroundings of the Ritz hotel. Not to mention unlimited hot chocolate for me from a silver jug, and replenishment of all food.', :price_cents => 35, :price_currency =>'GBP')
Visit.create(:venue => 'Burj Al Arab', :city => 'UAE', :date => DateTime.strptime('09/14/201040911', '%m/%d/%Y'), :ambience => 3, :tea => 5, :scones => 5, :savoury => 5, :sweets => 5, :service => 5, :bonus => 2, :comments => 'The most opulent high tea so far. Fell down only on ambience, because it was very Dubai-fabulous/Star-City. There was so much food, and lots of replenishment of drinks and food. We could try as many different teas as we liked - I had 3 pots.
The food included;
Champagne/Sparkling date juice
Fresh berries with cream
Wide range of teas
Rotisserie of the day was a beautiful salmon wrapped in pastry thing
Fancy sandwiches
Seafood plate/hor doevres
Fruit cakes, shortbreads, Creme brullee
Patisserie
Scones with mousse, jams and cream
Petit fours
A special chocolate mousse cake because it was my birthday.', :price_cents => 1, :price_currency =>'DIR')
Visit.create(:venue => 'Peninsula', :city => 'Hong Kong', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 4.5, :tea => 3.5, :scones => 3.75, :savoury => 5, :sweets => 4.5, :service => 5, :bonus => 0, :comments => 'Tracy did not go because she couldn\'t be bothered waiting in the line. 
Stupid', :price_cents => 350, :price_currency =>'HKD')
Visit.create(:venue => 'QVB Tea Rooms', :city => 'Australia', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 4, :tea => 4, :scones => 3.75, :savoury => 4, :sweets => 2, :service => 5, :bonus => 2, :comments => 'Make a comment', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Victoria Room', :city => 'Australia', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 5, :tea => 4.5, :scones => 3.5, :savoury => 3, :sweets => 4, :service => 3.5, :bonus => 0, :comments => 'This is a beautiful bar/restaurant to have high tea at, but I recently went again (early 2010), and found the ambience had fallen dramatically because it was just too crowded and noisy. They serve Turkish apple tea, which is one of my favourites.', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Observatory (Sue)', :city => 'Australia', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 4, :tea => 3, :scones => 4, :savoury => 4, :sweets => 4, :service => 3.5, :bonus => 0, :comments => 'Sue and I rated the Observatory from 2 separate occasions', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Bab Al Shams', :city => 'UAE', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 4.5, :tea => 4, :scones => 4.5, :savoury => 3, :sweets => 2.5, :service => 3, :bonus => 0, :comments => 'Went for my 30th (also told Burj Al Arab was my birthday), loved the ambience, loved the Emirati tea.', :price_cents => 1, :price_currency =>'DIR')
Visit.create(:venue => 'Lilianfels, Blue Mountains', :city => 'Australia', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 3.5, :tea => 3.5, :scones => 4, :savoury => 3, :sweets => 3.5, :service => 4, :bonus => 0, :comments => 'Sue to provide notes', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Sofitel', :city => 'Australia', :date => DateTime.strptime('09/14/201740918', '%m/%d/%Y'), :ambience => 3, :tea => 3, :scones => 4, :savoury => 4, :sweets => 3, :service => 3.5, :bonus => 0, :comments => 'Nothing of note, generic hotel high tea. Nice enough.', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Observatory (Tracy)', :city => 'Australia', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 4, :tea => 4.5, :scones => 3.5, :savoury => 2, :sweets => 5, :service => 1, :bonus => 0, :comments => 'The bad service probably stemmed from the fact it was over 20 people. But we didn\'t get our tea until we had eaten quite a lot. Crème brulee was the best I have ever had.', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Westin', :city => 'Australia', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 1, :tea => 3, :scones => 4, :savoury => 3, :sweets => 4, :service => 2, :bonus => 0, :comments => 'Hotel lobby, so not great ambience. Bizarre tennis themed food.', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Seibu', :city => 'Hong Kong', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 1, :tea => 3, :scones => 3, :savoury => 4, :sweets => 4.5, :service => 1, :bonus => 0, :comments => 'This is where we went after we couldn\'t be bothered waiting in line at the Peninsula. Basically, it is in a (nice) supermarket cafe. BUT the food was nice enough, even if the ambience and service were not.', :price_cents => 1, :price_currency =>'HKD')
Visit.create(:venue => 'Swissotel, Sydney', :city => 'Australia', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 1, :tea => 4, :scones => 3, :savoury => 3, :sweets => 2, :service => 1, :bonus => 2, :comments => 'This was the most entertaining of all the high teas, we were laughing a lot of the time, due to the combination of the demographic, \'fancy\' dress of the hens parties, and buffet-pigness. The replenishment points come from the fact it was a buffet, but buffet really does ruin the ambience', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Alice\'s Teacup, West 84th St, NYC', :city => 'USA', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 4, :tea => 4, :scones => 1, :savoury => 2, :sweets => 2, :service => 2, :bonus => 0, :comments => 'This was a normal café, not a proper high tea. They bizarro\'d it up by serving a plate of wilted spinach, poached eggs, very weird scones, yoghurt and berries, and not really any cakes or sandwiches. But I give points for trying, and they get good ambience because it was in an Alice in Wonderland themed cafe', :price_cents => 1, :price_currency =>'USD')
Visit.create(:venue => 'Etihad Business Class - Aus-UAE', :city => 'International Waters', :date => DateTime.strptime('09/14/202340924', '%m/%d/%Y'), :ambience => 2, :tea => 3, :scones => 1, :savoury => 3, :sweets => 2, :service => 3, :bonus => 0, :comments => 'Pretty cool to have high tea in business class on a plane, but can\'t really expect it to compare to restaurant food.', :price_cents => 0, :price_currency =>'AUD')
Visit.create(:venue => 'Sheraton on the Park', :city => 'Australia', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 1, :tea => 4, :scones => 4, :savoury => 2, :sweets => 1, :service => 0, :bonus => 0, :comments => 'The ambience was terrible, in that it is a hotel lobby and facing the road. There was next to no service, not even when we wanted to pay the bill. We went for the \'fancier\' version of the high tea, but the food was no good, and not really high tea food at all. Had Max Brennar HC which seemed a good idea, but does not go well with high tea. There is the option of buffet also, glad did not take it.', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'The Plaza Hotel', :city => 'NYC', :date => DateTime.strptime('09/14/202540926', '%m/%d/%Y'), :ambience => 4, :tea => 3, :scones => 4, :savoury => 4, :sweets => 5, :service => 3.5, :bonus => 0, :comments => 'We did the New Yorker high tea so had canolli, NYcheescake, cup cake, black and white cookie, lemon cake, fruit tart..I also had champagne', :price_cents => 1, :price_currency =>'USD')
Visit.create(:venue => 'Disneyland Hong Kong', :city => 'Hong Kong', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 3.5, :tea => 2, :scones => 3.5, :savoury => 3, :sweets => 3.5, :service => 3, :bonus => 0, :comments => 'Very cute, but of course the food wasn\'t ideal, and there wasn\'t even tea top up. The best was that you could get out of the heat and crowds, and have a view of the MAin street parade. Lots of Mickey shaped things.', :price_cents => 1, :price_currency =>'HKD')
Visit.create(:venue => 'Sir Stamford Circular Quay', :city => 'Sydney', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 5, :tea => 4, :scones => 4, :savoury => 3, :sweets => 3, :service => 3, :bonus => 0, :comments => 'Make a comment', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Peninsula Tracy', :city => 'Hong Kong', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 4.5, :tea => 4, :scones => 4, :savoury => 3.5, :sweets => 2.5, :service => 4.5, :bonus => 0, :comments => 'Nice, just don\'t like the line, excellent service, ambience a bit boring, but no big complaints(Tea a bit cold)', :price_cents => 1, :price_currency =>'HKD')
Visit.create(:venue => 'Waldorf Astoria Shanghai', :city => 'Shanghai', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 3.5, :tea => 4, :scones => 4.5, :savoury => 5, :sweets => 2.5, :service => 3.5, :bonus => 0, :comments => 'Peacock Alley - means, not a room, but actually on the thoroughfare!So it lost a bit of ambience. Savouries wer eprobably the best ever, BUT lost points because they didn\'t give us two of each. insane. The price was very low though.', :price_cents => 1, :price_currency =>'CNY')
Visit.create(:venue => 'Lilianfels, Blue Mountains', :city => 'Blue Mountains', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 5, :tea => 5, :scones => 5, :savoury => 5, :sweets => 5, :service => 5, :bonus => 2, :comments => 'Make a comment', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Kempinskii', :city => 'St Petersburg', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 5, :tea => 5, :scones => 5, :savoury => 5, :sweets => 5, :service => 5, :bonus => 2, :comments => 'Make a comment', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Ritz Hotel', :city => 'Paris', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 5, :tea => 5, :scones => 5, :savoury => 5, :sweets => 5, :service => 5, :bonus => 2, :comments => 'Make a comment', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Shangri-La', :city => 'Sydney', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 5, :tea => 5, :scones => 5, :savoury => 5, :sweets => 5, :service => 5, :bonus => 2, :comments => 'Make a comment', :price_cents => 1, :price_currency =>'AUD')
Visit.create(:venue => 'Ravenswood', :city => 'Wollongong', :date => DateTime.strptime('09/14/2009', '%m/%d/%Y'), :ambience => 2, :tea => 2, :scones => 2, :savoury => 3.5, :sweets => 2.5, :service => 1, :bonus => 0, :comments => 'the room was way too loud, and on a round table couldn\'t hear what anyone else at the table was saying. (wooden floor boards and two hens parties in same room). The tea came out about 45 minutes after the food, and then it was just a box of tea they plunked on the table and told us to choose from, but because of the awkward shape of the table, I had to get up and read them out to everyone. The chai tea I chose was yuck, and the cups were too big, and the sugar was from sachets. The scones were extremely salty, and the jam liquidy. The sandwiches were the highlight, but the only savoury was three finger sandwiches each. The sweets were all round disappointing, the service was almost non existent - friendly when they were there, which was hardly ever.', :price_cents => 1, :price_currency =>'AUD')




